name_max_leng: 55
email_max_leng: 255
phone_min_leng: 10
phone_max_leng: 15
pass_min_leng: 6
image_type: "image/jpeg,image/gif,image/png"
product_max_leng: 15
products_per_page: 50
description_limit: 700
min_qty: 1
max_qty: 20
